[Blindar-118] post user
blinder-23/blindar-iOS pull request #2
Opened 2024-07-27 09:48 UTC by sujileelea

## 주요 작업 내용

- 애플 로그인 -> 닉네임 입력 -> 학교 선택 -> ProgressView with cancel feature -> 달력 뷰
- 닉네임 필드 검증 완료 (중복 제외)
- UX 증진을 위해 user post 작업 진행 중 ProgressView를 띄우고 취소 버튼을 추가해 사용자가 작업을 취소할 수 있게 함

2024-07-27 10:20 UTC, mwy3055 requested changes
큰 문제는 없고, 작은 요청사항 몇개만 드릴게요

2024-07-27 10:20 UTC, mwy3055 commented on Blindar/View/Entry/NicknameNavigationPage.swift
> +}
이거 valid/invalid 케이스 나눠서 테스트 코드 작성해주세요. 잘 구현하신 거 같은데 혹시나 해서요

2024-07-27 10:20 UTC, mwy3055 commented on Blindar/API/UserAPI.swift
> +                        print("\(key): \(stringValue) (String)")
`print`는 디버깅 용도인가요? 디버깅 완료됐다면 지워주세요

2024-07-27 10:20 UTC, mwy3055 commented on Blindar/ViewModel/UserViewModel.swift
> +                NotificationCenter.default.post(name: NSNotification.Name("UserRegistered"), object: nil)
이건 무슨 notification을 보내는 건가요?

2024-07-28 09:37 UTC, sujileelea commented on Blindar/ViewModel/UserViewModel.swift
> +                NotificationCenter.default.post(name: NSNotification.Name("UserRegistered"), object: nil)
앱 내부로 notification을 보내서 post user의 비동기 작업이 끝나면 View에게 알려주어 사용자의 화면을 학교 선택 화면 -> 달력 화면으로 이동시켜주는 역할을 합니다. UI 상에는 보이지 않아요.

2024-07-28 09:42 UTC, sujileelea commented on Blindar/View/Entry/NicknameNavigationPage.swift
> +}
enum case 말씀하시는건가요?

2024-07-28 09:43 UTC, sujileelea commented on Blindar/View/Entry/NicknameNavigationPage.swift
> +}
아니면 별도로 테스트 코드 작성??

2024-07-28 09:59 UTC, mwy3055 commented on Blindar/View/Entry/NicknameNavigationPage.swift
> +}
입력 nickname에 대해 valid/invalid를 판단하는 테스트 코드요

2024-07-30 03:39 UTC, sujileelea commented on Blindar/View/Entry/NicknameNavigationPage.swift
> +}
이미 작성되어 있는 거 아닌가요? 잘 이해를 못했습니다.

2024-07-30 03:40 UTC, sujileelea commented on Blindar/API/UserAPI.swift
> +                        print("\(key): \(stringValue) (String)")
지우기 완~

2024-07-30 13:35 UTC, mwy3055 commented on Blindar/View/Entry/NicknameNavigationPage.swift
> +}
제가 언급한 테스트 코드는 "단위 테스트"입니다. 여러 가지 입력을 넣어봤을 때 함수가 올바르게 동작하는지 확인하는 테스트를 말합니다.

예를 들어, 안드로이드 앱의 `DateUtil.toDateString()` 함수를 테스트하는 코드는 다음과 같습니다.

https://github.com/blinder-23/blindar-android/blob/main/core/util/src/test/java/com/practice/util/DateUtilTest.kt

2024-08-03 06:22 UTC, merged